#В данном файле указываем анййстройки взаимодействия с базой данных
# При этом данный фаил более новый aplliclation.proprietes
# Тут мы прописываем настройки подключения к базе данных
#После введения спринг бут узнает настройки для подключения
#Затем спрва в столбце, где указана мэйвен вводим профиль и нам откроется консоль для рабоыт с БД

spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
   username: postgres
   password: 12345
  driver-class-name: org.postgresql.Driver

#Так же мы здесь можем пропсиать настройки для спринг дата жпа
# Эта библиотке позволяет нам на первых этапах разработки при -
# старте выполнять миграцию(создание таблиц и заполнение данными)
# и нам не нужно будет все это вводить в консоли или в пг админ


  sql:
# инит - при каждом запуске программы
# mode - режим (всегда), можно поставить never иначе выдает ошибку записи в БД, так как данные уже есть
    init:
      mode: always
      continue-on-error: false
# что бы не было ошибки заккоментируем путь к вставке данных
# data-locations: classpath:demo_data.sql

security:
  jwt:
    secret: ZGZhc3Zkdmxkam5oa2pmaGZkc2todmloYm9pZGZodm9pZmR2b2l1ZmhvaWRmdWhmaW9oZnVpb2Zodm9pTEZKSE9JRlVIDQo=
    access: 1
    refresh: 30


