#В данном файле указываем анййстройки взаимодействия с базой данных
# При этом данный фаил более новый aplliclation.proprietes
# Тут мы прописываем настройки подключения к базе данных
#После введения спринг бут узнает настройки для подключения
#Затем спрва в столбце, где указана мэйвен вводим профиль и нам откроется консоль для рабоыт с БД

spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
   username: postgres
   password: 12345
  driver-class-name: org.postgresql.Driver

#Так же мы здесь можем пропсиать настройки для спринг дата жпа
# Эта библиотке позволяет нам на первых этапах разработки при -
# старте выполнять миграцию(создание таблиц и заполнение данными)
# и нам не нужно будет все это вводить в консоли или в пг админ


  sql:
# инит - при каждом запуске программы
# mode - режим (всегда), можно поставить never иначе выдает ошибку записи в БД, так как данные уже есть
    init:
    # было бы алвейс,тогда работа, а сейчас отключили так, как миграция работает через ликвибейс
      mode: never
      continue-on-error: false
# что бы не было ошибки заккоментируем путь к вставке данных
# data-locations: classpath:demo_data.sql
#далее приступаем к настройке майбатис и что мы делаем- это мы устанавливааем путь к намим мэпперам, которые у нас 
#будут в xml

# Делаем миграцию через ликвибейс,при этом указываем чэндж лог,где будет инфа про таблицу
#и схему указываем таск лист(она должна быть создана уже) и тогда все будет в нее вставляться 
#энейбли говорит о том,что ликви бесй сейчас включена
   liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
    
mybatis:
mapper-locations: classpath: mybatis/mappers/*.xml

security:
  jwt:
    secret: ZGZhc3Zkdmxkam5oa2pmaGZkc2todmloYm9pZGZodm9pZmR2b2l1ZmhvaWRmdWhmaW9oZnVpb2Zodm9pTEZKSE9JRlVIDQo=
    access: 1
    refresh: 30


